### ISSUE TITLE
Navigation sidebar

### ISSUE THREAD

**Issue by scottrish** [openedx/platform-roadmap#231]
### Abstract

Allow site operators to optionally restore the course navigation sidebar that was present pre-Juniper.
Feedback from users and stakeholders indicates that the inability to immediate orientate themselves in the course, and the inability to navigate via the course outline without having to navigate to the course home page are sometimes considered negatives relative to Open edX competitors.

### Context & Background

Pre-Juniper the course outline was persistently displayed on the courseware pages allowing users to easily navigate non-linearly and orient themselves in the course.  In Juniper the course outline was removed from the courseware page and moved to the course home page, requiring users to navigate away from the courseware in order to jump to different sections or sub-sections.  This was partially mitigated by enhancing breadcrumbs allowing users to select a subsection from a dropdown hanging off a breadcrumb.
This initiative allows site deployers to optionally restore the nav sidebar which will be displayed in an MFE  to the left of the courseware. The course outline can be expanded and collapsed, and can also be shown/hidden.  Completion checkmarks will be displayed as the user completes subsections.
On mobile web, the display will toggle between displaying the outline full screen, and showing the content.
Example from the proof of concept:
<img width="816" alt="NavSidebar" src="https://user-images.githubusercontent.com/5141663/219091309-5493bd97-ab87-49c0-820f-653495c24f95.png">

Live demo - https://mfe-sandbox.pearson.com/learning/course/course-v1:edX+DemoX+Demo_Course/home
Note, this sandbox could be taken down without notice, or could be updated/reinstalled without preserving data.

### Scope & Approach

TBD

### Value & Impact

A course outline view that can be shown/hidden alongside the course content is a very common UI paradigm that users are comfortable with.
Subjective feedback to the proof of concept has been very positive when comparing the same course presented without the nav sidebar.

### Milestones and/or Epics

TBD

### Named Release

Q?

### Timeline

A proof of concept has already been developed and can be demo'd. Development is on hold until we have completed our upgrade to Olive, and we need some UX review and input.
We expect to deliver by end of 1H2023.

### Proposed By

Pearson

**Comment by DeanJayMathew** [comment]
This is great. It's a must-have feature, we need it back :)

Dean Jay Mathew
Director, ABC Online Courses Limited

Trusted Open edX® Service Providers since 2015
Schedule a meeting with me: https://calendly.com/abconlinecourses
View Our Website <http://www.abconlinecourses.com>
Tel.: +441225293341
Registered Address: Chestnut House
***@***.***,-2.1459131,15z/data=!3m1!4b1!4m8!1m2!2m1!1schestnut+house+53d+beanacre+sn127py!3m4!1s0x48717c9105a9d3d7:0x15804f821ad57207!8m2!3d51.3980641!4d-2.1374675>
(Wiltshire, England, UK)



*Legal Disclaimer: **This email and any files transmitted with it are
confidential and intended solely for the use of the individual or entity to
whom they are addressed and intended. If you have received this email in
error please notify the sender or system manager immediately. This message
contains confidential information and is intended only for the individual
named. If you are not the named addressee you should not disseminate,
distribute or copy this e-mail. Please notify the sender immediately by
e-mail if you have received this e-mail by mistake and delete this e-mail
from your system. If you are not the intended recipient you are notified
that disclosing, copying, distributing or taking any action in reliance on
the contents of this information is strictly prohibited.*

**Comment by jmakowski1123** [comment]
cc: @mariajgrimaldi 

Open spec (possibly implementation) questions:

- How the overall layout could be a configuration choice, sidebar versus current navigation, for example.

- How we might support user selectable modes longer "no distractions mode.

- Should the sidebar include units in the outline? It's currently limited to sections and subsections. If yes, then should the sidebar replace/coexist with/duplicate the horizontal unit navigation?

- UX/UI - Pros/cons of implementing as a widget in the sidebar, vs as a hover/floating box. Consider current sidebar projects already in place that may clash with the space, including notifications [need link] and Studio redesign work [need link].

**Comment by abstract-technology** [comment]
hi, 

Many of our customers ask for a different learning experience for learners regarding the course navigation sidebar to follow the content structure (and to have a view of all units which is not available in the course outline) and the completion. We are experimenting with customising the Learning MFE app and would like to hear some feedback from you all as open edx experts. We have prepared two small videos to show a first impression and results. Feel free to add feedback and ideas on how we could improve.
https://vimeo.com/901187445
https://vimeo.com/901187836

**Comment by jmakowski1123** [comment]
> hi,
> 
> Many of our customers ask for a different learning experience for learners regarding the course navigation sidebar to follow the content structure (and to have a view of all units which is not available in the course outline) and the completion. We are experimenting with customising the Learning MFE app and would like to hear some feedback from you all as open edx experts. We have prepared two small videos to show a first impression and results. Feel free to add feedback and ideas on how we could improve. https://vimeo.com/901187445 https://vimeo.com/901187836

Thanks for sharing these, Stefania. Looking forward to the group discussion next week.

**Comment by crathbun428** [comment]
Hello! I've added [this ticket](https://github.com/openedx/platform-roadmap/issues/329) to the backlog and marked it as in-progress to reflect the current work being done to re-introduce the left-sidebar navigation requested in this ticket. I'll be closing this ticket to avoid any confusion/duplication of efforts here. Thank you for raising this request.
