### ISSUE TITLE
Improved File Management on Files & Uploads Page

### ISSUE THREAD

**Issue by e0d** [openedx/platform-roadmap#247]
### At-A-Glance

Enhancements include:

-Better UI/workflow for bulk upload
-Options for bulk delete
-Better UI for individual file metadata view
-Sort and filter options (sort A-Z)
-Download individual files
-Download all files in a zip file
-Toggle view and grid view

Being built on a new MFE.

### More information

**Product specs**

**Design files**

- 

**Kanban board** 

### Stakeholders

Primary Contributors

- edX

### Community release milestones

- **Quince:** Released in Quince

- **Redwood:** 

### How to contribute

- [x] Has a community backlog with work to pick up?

**Comment by jmakowski1123** [comment]
The Studio team at 2U is working on a prototype for a nested file management system in Pages & Resources for authors to organize course uploads. @cablaa77 could you provide some additional details on scope/specs?

**Comment by bryan-kersten** [comment]
As Jenna mentioned above, my Studio team at 2U has a redesign of the Files & Uploads tab as a priority on their roadmap. The goals include the introduction of a folder structure and mechanisms for bulk delete.

**Comment by jmakowski1123** [comment]
Collaborators:
-Spanish use cases

**Comment by felipemontoya** [comment]
As I mentioned in the call, @santiagosuarezedunext and me definitely be interested in collaborating in this. Initially we'll be interested in the presentation of the files to the students

**Comment by cablaa77** [comment]
This is part of the larger Studio redesign initiative. The first part of this is to slice deliverables by page. We can convert the page and then reroute traffic from studio to course-authoring  just for the page. This should make it easier to roll out these changes across all of Studio experience, while getting a little more value from each deliverable.

We do not want to change functionality when we replace a tech stack. Replacing a tech stack should enable fast-feature-change after it lands. So in order to ensure successful delivery of various changes, we should keep feature change and tech stack change as independent deliverables e.g. MFE the Files and Uploads page first and then introduce new functionality/features.


The primary lens through which we look at new functionality and prioritization is to what degree the change will impact authoring efficiency, whether the given change will impact not only external but also internal edx.org partners (Bootcamps, Executive Education, Degrees), and whether the change will help us to execute on our platform strategy (more new courses and more new students).


Files and Uploads (after MFE)
New functionality/UX is still in the discovery phase. This discovery includes pain points highlighted by  edx.org platform map interviews (edX power user interviews), survey responses, and various online and in person conversations with partner administrators, staff, course authors and instructional designers. The current list of requirements, which is subject to change, includes
- Offer a folder structure 
- Bulk delete static assets with checkboxes
- Delete all files capability
- Include an indication which section/unit/component an asset has been published to 
- In context files so that author does not have to go to Files and Uploads  page while creating/editing content
- Folders across courses (probably out of scope for Studio redesign work)
- Folders across institutions (probably out of scope for Studio redesign work)

**Comment by walterpmtorres** [comment]
Hi @jmakowski1123 @bryan-kersten as mentioned during our meeting last Friday, here are Ignacio's videos about the folder/file management with Sakai LMS. 
https://youtu.be/8C4NT4jwz8U

**Comment by jmakowski1123** [comment]
Status update 7/20:

Should be ready for internal testing soon. The big parts in terms of new functionality are bulk actions and asset info. I would just say that this will be beta tested in August. Folders are after v2 content libraries and probably just for files in q4.

**Comment by jmakowski1123** [comment]
Update 8/16 - We're considering new features around file management in some early product discovery work around next phases for content libraries. Target having conceptual designs to share in Oct/Nov.

**Comment by bryan-kersten** [comment]
2U Update: We are working through internal testing and bug resolution for rollout of our next version of Files (features noted in 7/20 update). We are targeting beta testing period to begin within the next few weeks.

**Comment by bryan-kersten** [comment]
2U Update: Files is currently in beta and we are addressing issues that our beta testers are identifying.
