### ISSUE TITLE
[Pull request] Option to include ungraded subsections in progress page

### ISSUE THREAD

**Issue by navinkarkera** [openedx/platform-roadmap#359]
### Abstract

The legacy progress page had an option to display ungraded subsections which is missing from the new learning MFE. So to keep feature parity with legacy, we have created a PR: https://github.com/openedx/frontend-app-learning/pull/1380 to add it. It can be enabled by setting a flag in `MFE_CONFIG`.

### Milestones and/or Epics

PR: https://github.com/openedx/frontend-app-learning/pull/1380

### Named Release

Redwood

### Proposed By

OpenCraft

### Additional Info

**Comment by ali-hugo** [comment]
@itsjeyd The product review for this PR is complete. I've changed the label to indicate as much, but am unsure which column to place this ticket into. Should it go into "backlog" now?

**Comment by itsjeyd** [comment]
@ali-hugo Since this is a feature ticket (and not a PR on the Contributions board), that's a question for @jmakowski1123, or perhaps the product working group as a whole 🙂 

Updating tickets on the roadmap is out of scope for OSPR managers, and I'm not sure that I know the latest on how the different board columns are supposed to be used. That said, based on a brief look it seems like Being Developed would be a good fit? (We already have a PR with code changes for this feature.)

Either way, I'll take care of updating the PR that belongs to this feature ticket (https://github.com/openedx/frontend-app-learning/pull/1380) on the Contributions board.

**Comment by itsjeyd** [comment]
@ali-hugo 

> Updating tickets on the roadmap is out of scope for OSPR managers, ...

And vice versa: It would probably make sense to consider updating PRs on the Contributions board (changing status and/or labels) out of scope for product proposal coordinators.

That way the two groups (product working group, OSPR managers) won't be stepping on each others toes. And instead of having to become (and stay) familiar with two distinct workflows, members of each group could just focus on the workflow that's most relevant to them.

CC @mphilbrick211 @jmakowski1123

**Comment by ali-hugo** [comment]
@itsjeyd Thanks for the explanation. It makes sense to me to keep the two workflows separate.

I will make some suggestions on the [product review procedure](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review) and ping Michelle, Jenna, and Sarina to approve them.

**Comment by itsjeyd** [comment]
Awesome, thanks @ali-hugo!

I'm watching that page so you can consider me in the loop for any updates that you make.
